### ISSUE TITLE
Error after installing plugin 

### ISSUE THREAD

**Issue by frh3ddy** [Tcheu/craftcms-httprequest#1]
Hi. 

Right after I install the Plugin, I get this error message 
Template Error
Method "getPath" for object "Craft\HttpRequestVariable" does not exist

It happens on the control panel and also in the frontend. 

I have to rename the folder of the plugin to get craft working again, Do you know what could cause this error? I have the lasted craft update. 
Craft Pro 2.4.2670 Released on 6/16/2015

**Comment by kant312** [comment]
Hi and thanks for reporting this,

I was not aware of that, but it seems that Craft already declares an HttpRequestVariable class (http://buildwithcraft.com/classreference/variables/HttpRequestVariable), thus there is a conflict.

Weirdly, I did not encounter the problem, not even after installing a fresh new version of Craft.
The only solution seems to find another name for the plugin, which is a bit hard since it should be really clear on what it is doing, and at the same time the subject encourages names collisions.

I'll update this ticket once I find the new name and refactored.

If you need the plugin immediately, a good workaround would be to rename the plugin and the classes accordingly, in order to avoid the name collision.

**Comment by kant312** [comment]
I renamed the plugin handle to "httpReq" and updated the documentation accordingly. This should do the trick...
